### ISSUE TITLE
Race condition failures: lost logs and failtures

### ISSUE THREAD

**Issue by KanstantsinSudzilouski** [reportportal/logger-java-log4j#3]
**Setup**:

1. Java 1.8.0_141, logger-java-log4j 3.0.2; agent-java-testng 3.0.6; log4j 1.2.16; testng 6.11; server hosted at rp.epam.com
2. Appender     `<appender name="ReportPortalAppender" class="com.epam.ta.reportportal.log4j.appender.ReportPortalAppender">` added to log4j.xml file
3. Listener `<listener class-name="com.epam.reportportal.testng.ReportPortalTestNGListener" />` added to testng.xml

**Issue 1**
If we try to log messages immediately after test starts, it not get logged to RP.
```
  @Test
  public void myTest() throws InterruptedException {
    LOG.info("Begin");
    Thread.sleep(100);
    LOG.info("some time ago " + System.currentTimeMillis());
  }
```
In this example message "Begin" will be missed in RP logs.

**Issue 2**
If test runs very fast (no more than 10-50 ms) it fails.
```
  @Test
  public void myTest() throws InterruptedException {
    LOG.info("Begin");
  }
```
Error log:

```
2017-09-25 10:30:29,814 [Thread: I/O dispatcher 1]   DEBUG PoolingNHttpClientConnectionManager - Connection released: [id: http-outgoing-0][route: {s}->https://rp.epam.com:443][total kept alive: 2; route allocated: 2 of 2; total allocated: 2 of 20]\
io.reactivex.exceptions.OnErrorNotImplementedException: Report Portal returned error
Status code: 406
Status message: Not Acceptable
Error Message: Start test item is not allowed. Parent Item '[skipped]' already has log items
Error Type: START_ITEM_NOT_ALLOWED

	at io.reactivex.internal.functions.Functions$14.accept(Functions.java:229)
	at io.reactivex.internal.functions.Functions$14.accept(Functions.java:226)
	at io.reactivex.internal.operators.maybe.MaybeCallbackObserver.onError(MaybeCallbackObserver.java:81)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeOnMaybeObserver.onError(MaybeSubscribeOn.java:96)
	at io.reactivex.internal.operators.maybe.MaybeCache.onError(MaybeCache.java:103)
	at io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver$InnerObserver.onError(MaybeFlatten.java:125)
	at io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver$InnerObserver.onError(MaybeFlatten.java:125)
	at io.reactivex.internal.operators.maybe.MaybeMap$MapMaybeObserver.onError(MaybeMap.java:94)
	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onErrorInner(MaybePeek.java:147)
	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onError(MaybePeek.java:134)
	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onErrorInner(MaybePeek.java:147)
	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onError(MaybePeek.java:134)
	at io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver.onError(MaybeFlatten.java:103)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeOnMaybeObserver.onError(MaybeSubscribeOn.java:96)
	at io.reactivex.internal.operators.maybe.MaybeCache.onError(MaybeCache.java:103)
	at io.reactivex.internal.operators.maybe.MaybeCreate$Emitter.onError(MaybeCreate.java:94)
	at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.completed(HttpClientRestEndpoint.java:569)
	at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.completed(HttpClientRestEndpoint.java:518)
...
```
If I remove log4j appender, Issue 2 not reproduced.

**Comment by avarabyeu** [comment]
will be processed in 4 milestone
